# py2exe script for win32 
# setup.py
from distutils.core import setup
import py2exe
      
setup(windows=["blindmine.py"],
    data_files=[(".", ["freesansbold.ttf", "LICENSE", "blindmine.py", "sdl_ui.py", "howto.txt", "README", "LICENSE", "opening.txt", "util.py", "game.py", "setup1.py", 
	]),
	("data", [
"data/1.wav",
"data/0.wav",
"data/1.wav",
"data/10.wav",
"data/100.wav",
"data/1000.wav",
"data/2.wav",
"data/3.wav",
"data/4.wav",
"data/5.wav",
"data/6.wav",
"data/7.wav",
"data/8.wav",
"data/9.wav",
"data/bad.wav",
"data/comma.wav",
"data/current_position.wav",
"data/elapsed_time.wav",
"data/flag2.xpm",
"data/flagged.wav",
"data/howto.ogg",
"data/invalid.wav",
"data/mine.wav",
"data/mine2.xpm",
"data/n0.wav",
"data/n1.wav",
"data/n10.wav",
"data/n11.wav",
"data/n12.wav",
"data/n13.wav",
"data/n14.wav",
"data/n15.wav",
"data/n16.wav",
"data/n2.wav",
"data/n3.wav",
"data/n4.wav",
"data/n5.wav",
"data/n6.wav",
"data/n7.wav",
"data/n8.wav",
"data/n9.wav",
"data/number_of_flag.wav",
"data/number_of_mines.wav",
"data/object.wav",
"data/open.wav",
"data/opening.ogg",
"data/openmany.wav",
"data/out.wav",
"data/second.wav",
"data/sweep.wav",
"data/toolongtime.wav",
"data/underconstruction.wav",
"data/unflagged.wav",
"data/unknown.wav",
"data/won.wav",

		])
	]
)

